# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: daily_task

on:
  workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    env: # 设置环境变量
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSL_MODE: ${{ secrets.DB_SSL_MODE }}
      DB_TZ: ${{ secrets.DB_TZ }}
      API_URL: ${{ secrets.API_URL }}
      API_AUTH_KEY: ${{ secrets.API_AUTH_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_USER: ${{ secrets.REDIS_USER }}
      REDIS_PASSWD: ${{ secrets.REDIS_PASSWD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        run:
          ls
          pwd

      - name: collect_repository
        run: ./github-trending-collect -task trending -since daily

      - name: save_repository
        run: ./github-trending-collect -task repo -since daily
