name: daily_collect_task

on:
  schedule:
    - cron: '0 0/1 * * *' # 每三个小时的整点


jobs:
  collect_to_cache:
    name: collect github trending with interval three hours
    runs-on: ubuntu-latest
    env: # 设置环境变量
      NACOS_HOST: ${{ secrets.NACOS_HOST }}
      NACOS_PORT: ${{ secrets.NACOS_PORT }}
      NACOS_ID: ${{ secrets.NACOS_ID }}
      NACOS_TIMEOUT: ${{ secrets.NACOS_TIMEOUT }}
      NACOS_USERNAME: ${{ secrets.NACOS_USERNAME }}
      NACOS_PASSWORD: ${{ secrets.NACOS_PASSWORD }}
      NACOS_LEVEL: ${{ secrets.NACOS_LEVEL }}
      NACOS_DATA_ID: ${{ secrets.NACOS_DATA_ID }}
      NACOS_GROUP_ID: ${{ secrets.NACOS_GROUP_ID }}

    steps:
      - name: download github collect binary
        run: wget ${{ secrets.RELEASE_URL }} -O github-trending-collect.tar.gz && ls -lh

      - name: unpack tar package file
        run: /usr/bin/tar xf github-trending-collect.tar.gz && ls -lh

      - name: run collect script
        run: ./github-trending-collect -task trending -since daily