name: daily_save_task

on:
  schedule:
    - cron: '30 9 * * *' # 每天下午5点半
  workflow_dispatch: # 允许手动触发

jobs:
  save_to_db:
    name: save github trending info from cache in daily
    runs-on: ubuntu-latest
    env: # 设置环境变量
      NACOS_HOST: ${{ secrets.NACOS_HOST }}
      NACOS_PORT: ${{ secrets.NACOS_PORT }}
      NACOS_ID: ${{ secrets.NACOS_ID }}
      NACOS_TIMEOUT: ${{ secrets.NACOS_TIMEOUT }}
      NACOS_USERNAME: ${{ secrets.NACOS_USERNAME }}
      NACOS_PASSWORD: ${{ secrets.NACOS_PASSWORD }}
      NACOS_LEVEL: ${{ secrets.NACOS_LEVEL }}
      NACOS_DATA_ID: ${{ secrets.NACOS_DATA_ID }}
      NACOS_GROUP_ID: ${{ secrets.NACOS_GROUP_ID }}

    steps:
      - name: download github collect binary
        run: wget ${{ secrets.RELEASE_URL }} -O github-trending-collect.tar.gz && ls -lh

      - name: unpack tar package file
        run: /usr/bin/tar xf github-trending-collect.tar.gz && ls -lh

      - name: run save script
        run: ./github-trending-collect -task repo -since daily