
name: test_download

on: workflow_dispatch

jobs:
  test_binary:
    name: test github collect binary
    runs-on: ubuntu-latest

    steps:
      - name: download github collect binary
        run: wget https://github.com/zpzhue/github-trending-collect/releases/download/v0.1/github-trending-collect_0.1_linux_amd64.tar.gz -O github-trending-collect.tar.gz && ls -lh

      - name: unpack tar package file
        run: /usr/bin/tar xf github-trending-collect.tar.gz && ls -lh

      - name: run script
        run: ./github-trending-collect -h